[{"value"=>"OPERATING ACTIVITIES"},
 {"value"=>""},
 {"value"=>"Net Income"},
 {"value"=>"1551.21"},
 {"value"=>"Adjustments to reconcile Net Income to Net Cash provided by operations:"},
 {"value"=>""},
 {"value"=>"Accounts Receivable (A/R)", "id"=>"84"},
 {"value"=>"-4879.77"},
 {"value"=>"Inventory Asset", "id"=>"81"},
 {"value"=>"-596.25"},
 {"value"=>"Accounts Payable (A/P)", "id"=>"33"},
 {"value"=>"1602.67"},
 {"value"=>"Mastercard", "id"=>"41"},
 {"value"=>"157.72"},
 {"value"=>"Arizona Dept. of Revenue Payable", "id"=>"89"},
 {"value"=>"0.00"},
 {"value"=>"Board of Equalization Payable", "id"=>"90"},
 {"value"=>"360.44"},
 {"value"=>"Loan Payable", "id"=>"43"},
 {"value"=>"4000.00"},
 {"value"=>"Total Adjustments to reconcile Net Income to Net Cash provided by operations:"},
 {"value"=>"644.81"},
 {"value"=>"INVESTING ACTIVITIES"},
 {"value"=>""},
 {"value"=>"Truck:Original Cost", "id"=>"38"},
 {"value"=>"-13495.00"},
 {"value"=>"Net cash provided by investing activities"},
 {"value"=>"-13495.00"},
 {"value"=>"FINANCING ACTIVITIES"},
 {"value"=>""},
 {"value"=>"Notes Payable", "id"=>"44"},
 {"value"=>"25000.00"},
 {"value"=>"Opening Balance Equity", "id"=>"34"},
 {"value"=>"-14337.50"},
 {"value"=>"Net cash provided by financing activities"},
 {"value"=>"10662.50"},
 {"value"=>"Net cash increase for period"},
 {"value"=>"-636.48"},
 {"value"=>"Cash at beginning of period"},
 {"value"=>"4700.00"},
 {"value"=>"Cash at end of period"},
 {"value"=>"4063.52"}]
